name: Daily bing-rewards executable
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 19 * * *'
jobs:
  Run-On-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run Python Script
        env:
          MICROSOFT_EMAIL: ${{ secrets.MICROSOFTEMAIL }}
          MICROSOFT_PASSWORD: ${{ secrets.MICROSOFTPASSWORD }}
          TELEGRAM_API: ${{ secrets.TELEGRAMAPI }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAMUSERID }}

        run: |
          cd bing-rewards
          cd BingRewards
          pip install -r requirements.txt
          python BingRewards.py

  Run-On-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run Python Script
        env:
          MICROSOFT_EMAIL: ${{ secrets.MICROSOFTEMAIL }}
          MICROSOFT_PASSWORD: ${{ secrets.MICROSOFTPASSWORD }}
          TELEGRAM_API: ${{ secrets.TELEGRAMAPI }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAMUSERID }}
        run: |
          cd bing-rewards
          cd BingRewards
          pip install -r requirements.txt
          python BingRewards.py

  Run-On-MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run Python Script
        env:
          MICROSOFT_EMAIL: ${{ secrets.MICROSOFTEMAIL }}
          MICROSOFT_PASSWORD: ${{ secrets.MICROSOFTPASSWORD }}
          TELEGRAM_API: ${{ secrets.TELEGRAMAPI }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAMUSERID }}
        run: |
          cd bing-rewards
          cd BingRewards
          pip install -r requirements.txt
          python BingRewards.py